language: go
sudo: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python python-pip
    - sudo pip install tox nose
install:
- bash .travis-fork-fix
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
- curl https://glide.sh/get | sh
git:
  depth: 9999999
matrix:
  include:
  - go: 1.7.5
    env: OPTIONS="-race"
  - go: 1.8.2
    env: COVERAGE="true"
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- make
- if [[ -z "$COVERAGE" ]]; then make test TESTOPTIONS=-v ; fi
- if [[ -n "$COVERAGE" ]]; then make test TESTOPTIONS=-vcstdout && bash .travis-coverage; fi
- make release
